---
sudo: required
dist: trusty
language: python

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible through pip
  - sudo apt-get install -y python-pip python-dev
  - python --version
  - pip --version
  - sudo -H pip install ansible
  - ansible --version

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax:
  - ansible-playbook -i tests/inventory tests/provision-test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/decommission-test.yml --syntax-check
